# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - vtm-tank-site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Istall project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;

      - name: Install pytest and dependencies
        run: pip install pytest

      - name: Run test with pytest
        run: python -m pytest

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

  package:
    name: "package"
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Istall project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;

      - name: Create BUILD directory and copy necessary application files
        run: |
          mkdir BUILD
          cp -r static BUILD/static 
          cp -r templates BUILD/templates
          cp -r app.py BUILD/app.py
          cp -r requirements.txt BUILD/requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            ./BUILD

  deploy:
    runs-on: ubuntu-latest
    needs: package
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "vtm-tank-site"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_09445654843246FB8E2373AA6F9E6A18 }}
